IDENTIFICATION DIVISION.
PROGRAM-ID. DIVIDE-EXAMPLE.

DATA DIVISION.
WORKING-STORAGE SECTION.
01 DIVIDEND PIC 9(3) VALUE 100.
01 DIVISOR PIC 9(2) VALUE 5.
01 RESULT PIC 9(3).
01 REMAINDER PIC 9(2).

PROCEDURE DIVISION.
    DIVIDE DIVIDEND BY DIVISOR
    GIVING RESULT
    REMAINDER REMAINDER.
    
    DISPLAY "Result of division: " RESULT
    DISPLAY "Remainder: " REMAINDER.
    
    STOP RUN.
